#!/bin/bash

my_loc="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
df_home=$(dirname $my_loc)

os_name="..."
lx_cfghome=$XDG_CONFIG_HOME

mkdir -p ./_out/
mkdir -p ./_log/

uname_output=$(uname)
if [ $uname_output = "Linux" ]; then
  echo " INFO: Detected Linux system"
  os_name="linux"
  if [ -z $XDG_CONFIG_HOME ]; then
    lx_cfghome="~/.config"
  fi
elif [[ $uname_output == MINGW64_NT* ]]; then
  echo " INFO: Detected MINGW64 system -> Win64"
  os_name="win64"
elif [[ $uname_output == "Darwin" ]]; then
  echo " INFO: Detected MacOS system"
  os_name="macos"
else
  echo "ERROR: Unsupported OS!"
  echo "       Exiting with error..."
  exit 1
fi

if [ $os_name == "macos" ]; then
  cat snippet/kdfblockhead >> ~/.zshrc
else
  cat snippet/kdfblockhead >> ~/.bashrc
fi

if [ $KDF_WORKSPACE_TYPE ]; then
  if [ $KDF_WORKSPACE_TYPE = "ghcs" ]; then
    echo ' INFO: $KDF_WORKSPACE_TYPE indicates GitHub Codespace'
    if [ $KIRIDEVS_PAT ]; then
      echo ' INFO: $KIRIDEVS_PAT exists | patch::bashrc[codespaceKiriPat]'
      if [ $os_name == "macos" ]; then
        cat patch/bashrc-ghcsAuthentication.bash.kdfpatch >> ~/.zshrc
      else
        cat patch/bashrc-ghcsAuthentication.bash.kdfpatch >> ~/.bashrc
      fi
    fi
  fi
fi

if [ $PROMPT_COMPACT ]; then
  echo ' INFO: Detected $PROMPT_COMPACT | patch::bashrc[prompt]'
  if [ $os_name == "macos" ]; then
    cat patch/bashrc-promptcompactSupplied.bash.kdfpatch >> ~/.zshrc
  else
    cat patch/bashrc-promptcompactSupplied.bash.kdfpatch >> ~/.bashrc
  fi
fi

# Add aliases to bashrc
echo " INFO: set::bashAliases"
if [ $os_name == "linux" ]; then
  echo "source $df_home/_out/bashAliases" >> ~/.bashrc
  python3 script/generateBashAliases.py
elif [ $os_name == "macos" ]; then
  echo "source $df_home/_out/bashAliases" >> ~/.zshrc
  python3 script/generateBashAliases.py
else
  echo "source $df_home/_out/bashAliases" >> ~/.bashrc
  python script/generateBashAliases.py
fi

# Set up files depending on availability of specific features
if [ $os_name == "win64" ]; then
  findgitcmd="where git"
else
  findgitcmd="whereis git"
fi

if [ "$(eval $findgitcmd 2> /dev/null)" ]; then
  echo " INFO: Detected Git | script::setGitprefs"
  sh script/setGitprefs.sh
else
  echo " WARN: Didn't detect Git - are you sure your \$PATH is ok?"
fi

if [ "$(whereis nvim 2> /dev/null)" ]; then
  echo " INFO: Detected nvim | patch::bashrc[editor,visual] link::init.vim"
  if [ $os_name == "macos" ]; then
    cat patch/bashrc-nvimAvailable.bash.kdfpatch >> ~/.zshrc
  else
    cat patch/bashrc-nvimAvailable.bash.kdfpatch >> ~/.bashrc
  fi

  # Symlink the init.vim
  if [ $os_name == "linux" ]; then
    mkdir -p ~/.config/nvim
    ln -s $df_home/config/init.vim $lx_cfghome/nvim/init.vim
    echo "       $lx_cfghome/nvim/init.vim -> kdf::config/init.vim"
  elif [ $os_name == "win64" ]; then
    # Check for Administrator privileges
    if [[ $(sfc 2>&1 | tr -d '\0') =~ SCANNOW ]]; then
      mkdir -p ~/AppData/Local/nvim
      powershell -Command "New-Item -ItemType SymbolicLink -Path ~\AppData\Local\nvim -Name init.vim -Value .\config\init.vim"
      echo "       ~/AppData/Local/nvim/init.vim -> kdf::config/init.vim"
    elif [ $os_name == "macos" ]; then
      ln -s $df_home/config/init.vim ~/.config/nvim/init.vim
      echo "       .config/nvim/init.vim -> kdf::config/init.vim"
    else
      echo "ERROR: Missing Administrator privileges!"
      exit 1
    fi
  fi
fi

if [ $os_name == "macos" ]; then
  # The default shell on macOS is zsh
  echo " INFO: Inject Update into zshrc | patch::bashrc[selfUpdate]"
  cat patch/bashrc-selfUpdate.bash.kdfpatch >> ~/.zshrc
else
  echo " INFO: Inject Update into bashrc | patch::bashrc[selfUpdate]"
  cat patch/bashrc-selfUpdate.bash.kdfpatch >> ~/.bashrc
fi

echo "patch::bashrc[dfExport]"
if [ $os_name == "macos" ]; then
  echo "export DF=$df_home" >> ~/.zshrc
else
  echo "export DF=$df_home" >> ~/.bashrc
fi

if [ $os_name == "macos" ]; then
  cat snippet/kdfblockend >> ~/.zshrc
else
  cat snippet/kdfblockend >> ~/.bashrc
fi
